TrajectoryPlannerROS:
# DWAPlannerROS:
    dwa: false
    holonomic_robot: false
  # Robot Configuration Parameters
    acc_lim_x: 0.1 # 2.5
    acc_lim_y: 0.0
    acc_lim_theta: 10.0 # 0.5

    # The absolute velocity when robot is moving in a straight line (translational velocity)
    max_vel_trans:  1.0 # 0.55 # 0.52 # 0.26
    min_vel_trans:  0.0 # 0.15 # 0.13

    max_vel_x: 0.4 # 0.26
    min_vel_x: 0.0 # -0.55 # -0.26 # negative for backwards motion

    max_vel_y: 0.0
    min_vel_y: 0.0

    # The absolute value of rotational velocity
    max_vel_theta: 1.5 # 1.0
    min_vel_theta: -1.5 # 0.25

  # Goal Tolerance Parametes
    yaw_goal_tolerance: 0.1 # 0.1 radius = 5.7 degree
    xy_goal_tolerance: 0.1 # 1.0 = 1m
    latch_xy_goal_tolerance: false

  # Forward Simulation Parameters
    sim_time: 1.7 # 1.0
    sim_granularity: 0.025
    vx_samples: 6
    vy_samples: 1
    vth_samples: 20
    controller_frequency: 5.0

  # Trajectory Scoring Parameters
    path_distance_bias: 0.6 # 64.0
    goal_distance_bias: 0.8 # 24.0
    occdist_scale: 0.05 #0.5
    forward_point_distance: 1.0 # 0.325
    stop_time_buffer: 0.2
    scaling_speed: 0.25
    max_scaling_factor: 0.2
    publish_cost_grid: false

  # Oscillation Prevention Parameters
    oscillation_reset_dist: 0.1
  
  # Global Plan Paramters
    prune_plan: true

  # Debugging
    publish_traj_pc : true
    publish_cost_grid_pc: true